// Writes Adapters.fs: the delegate↔function adapter types, one per shape. Run from the repo root:
//     dotnet fsi FSharp.Interop.Dlr/generate-adapters.fsx
// The logic that picks and instantiates them (by name, via reflection) is in Binders.fs.

let out = System.Text.StringBuilder()
let line (s: string) = out.AppendLine s |> ignore

let ts n = [ for i in 1 .. n -> sprintf "'T%d" i ]
let ps n = [ for i in 1 .. n -> sprintf "t%d" i ]
let join (sep: string) (xs: string list) = String.concat sep xs
let typed n = [ for i in 1 .. n -> sprintf "t%d: 'T%d" i i ] |> join ", "
let args n = ps n |> join ", "
let generics (xs: string list) = if xs.IsEmpty then "" else "<" + join ", " xs + ">"

line "namespace FSharp.Interop.Dlr"
line ""
line "// Generated by generate-adapters.fsx; edit that script, not this file."
line ""
line "open System"
line "open System.Runtime.CompilerServices"
line ""
line "/// Typed F# functions over delegates, for a delegate argument passed to a function-typed"
line "/// parameter: the delegate is rebound once to the `Func`/`Action` of its signature (any delegate"
line "/// type with that signature works) and each wrapper calls `Invoke` directly — curried ones"
line "/// through `OptimizedClosures`, so `f a b` is one call. Up to five parameters; past that, a"
line "/// factory compiled once per pair (`FunctionBuilder`); no other shape is converted. The `Action`"
line "/// wrappers take a result type parameter (instantiated to `unit`) because an `FSharpFunc<_, unit>`"
line "/// must return the `Unit` object, which a method declared `: unit` (void) cannot."
line "/// Not part of the supported API: public only because compiled blocks call it, and it may change in any release."
line "[<System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)>]"
line "module DelegateFunctions ="
for n in 0 .. 5 do
    let tr = ts n @ [ "'R" ]
    let func = "Func" + generics tr
    let action = "Action" + generics (ts n)
    let unitTail = "; Unchecked.defaultof<'R>"
    if n = 0 then
        line (sprintf "    type Func0<'R>(d: %s) =" func)
        line "        inherit FSharpFunc<unit, 'R>()"
        line "        override _.Invoke(_: unit) = d.Invoke()"
        line (sprintf "    type Action0<'R>(d: %s) =" action)
        line "        inherit FSharpFunc<unit, 'R>()"
        line ("        override _.Invoke(_: unit) : 'R = d.Invoke()" + unitTail)
    elif n = 1 then
        line (sprintf "    type Func1<'T1, 'R>(d: %s) =" func)
        line "        inherit FSharpFunc<'T1, 'R>()"
        line "        override _.Invoke(t1: 'T1) = d.Invoke(t1)"
        line (sprintf "    type Action1<'T1, 'R>(d: %s) =" action)
        line "        inherit FSharpFunc<'T1, 'R>()"
        line ("        override _.Invoke(t1: 'T1) : 'R = d.Invoke(t1)" + unitTail)
    else
        let rest = ps n |> List.tail
        let curriedResult = "(" + join " -> " (List.tail (ts n) @ [ "'R" ]) + ")"
        for kind, d, tail in [ "Func", func, ""; "Action", action, unitTail ] do
            line (sprintf "    type %s%d%s(d: %s) =" kind n (generics tr) d)
            line (sprintf "        inherit OptimizedClosures.FSharpFunc%s()" (generics tr))
            line (sprintf "        override this.Invoke(t1: 'T1) : %s = fun %s -> this.Invoke(%s)" curriedResult (join " " rest) (args n))
            line (sprintf "        override _.Invoke(%s)%s = d.Invoke(%s)%s" (typed n) (if tail = "" then "" else " : 'R") (args n) tail)
        for kind, d, tail in [ "Func", func, ""; "Action", action, unitTail ] do
            line (sprintf "    type Tupled%s%d%s(d: %s) =" kind n (generics tr) d)
            line (sprintf "        inherit FSharpFunc<%s, 'R>()" (join " * " (ts n)))
            line (sprintf "        override _.Invoke((%s))%s = d.Invoke(%s)%s" (args n) (if tail = "" then "" else " : 'R") (args n) tail)
line ""
line "/// Delegates over F# functions, for an F# function argument passed to a delegate-typed parameter:"
line "/// one adapter per shape (curried/tupled × result/void, 0–16 parameters) whose `Invoke` method"
line "/// has the delegate's exact signature; `FunctionConversions` emits a factory per (function type,"
line "/// delegate type) over them."
line "/// Not part of the supported API: public only because compiled blocks call it, and it may change in any release."
line "[<System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)>]"
line "module FunctionAdapters ="
for n in 0 .. 16 do
    for result, suffix in [ "'R", ""; "unit", "Unit" ] do
        let tps = ts n @ (if suffix = "" then [ "'R" ] else [])
        let curriedType = join " -> " ((if n = 0 then [ "unit" ] else ts n) @ [ result ])
        line (sprintf "    type Curried%d%s%s(f: %s) =" n suffix (generics tps) curriedType)
        if n = 0 then
            line (sprintf "        member _.Invoke() : %s = f ()" result)
        elif n = 1 then
            line "        let f = f"
            line (sprintf "        member _.Invoke(t1: 'T1) : %s = f t1" result)
        elif n <= 5 then
            line (sprintf "        let f = OptimizedClosures.FSharpFunc%s.Adapt f" (generics (ts n @ [ result ])))
            line (sprintf "        member _.Invoke(%s) : %s = f.Invoke(%s)" (typed n) result (args n))
        else
            line "        let f = f"
            line (sprintf "        member _.Invoke(%s) : %s = f %s" (typed n) result (join " " (ps n)))
    if n >= 2 then
        for result, suffix in [ "'R", ""; "unit", "Unit" ] do
            let tps = ts n @ (if suffix = "" then [ "'R" ] else [])
            line (sprintf "    type Tupled%d%s%s(f: %s -> %s) =" n suffix (generics tps) (join " * " (ts n)) result)
            line (sprintf "        member _.Invoke(%s) : %s = f (%s)" (typed n) result (args n))

line ""
line "/// Delegates over a member's call sites, for a method read as a delegate type (#201): one invoker"
line "/// per shape (result/void, 0–14 parameters: the site's `Func`/`Action` takes the `CallSite` and the"
line "/// target too) holding the invoke site, the convert site and the target, whose `Invoke` has the"
line "/// delegate's exact signature; `FunctionConversions.over` binds the delegate to it. Past fourteen"
line "/// the site is wide, and the read goes through the member read as a function instead."
line "/// Not part of the supported API: public only because compiled blocks call it, and it may change in any release."
line "[<System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)>]"
line "module MemberInvokers ="
for n in 0 .. 14 do
    let site = "CallSite<Func" + generics ([ "CallSite"; "obj" ] @ ts n @ [ "obj" ]) + ">"
    let voidSite = "CallSite<Action" + generics ([ "CallSite"; "obj" ] @ ts n) + ">"
    let callArgs = join ", " ([ "invoke"; "target" ] @ ps n)
    line (sprintf "    type Func%d%s(invoke: %s, convert: CallSite<Func<CallSite, obj, 'R>>, target: obj) =" n (generics (ts n @ [ "'R" ])) site)
    line (sprintf "        member _.Invoke(%s) : 'R = convert.Target.Invoke(convert, invoke.Target.Invoke(%s))" (typed n) callArgs)
    line (sprintf "    type Action%d%s(invoke: %s, target: obj) =" n (generics (ts n)) voidSite)
    line (sprintf "        member _.Invoke(%s) : unit = invoke.Target.Invoke(%s)" (typed n) callArgs)

System.IO.File.WriteAllText(System.IO.Path.Combine(__SOURCE_DIRECTORY__, "Adapters.fs"), out.ToString())
printfn "Wrote Adapters.fs"
