// Writes Cases/*.g.fs: every case of the grammar (Grammar.fsx), for run.sh.
//   dotnet fsi generate.fsx

#load "Grammar.fsx"

open System.IO
open Grammar

let dir = Path.Combine(__SOURCE_DIRECTORY__, "Cases")
if Directory.Exists dir then Directory.Delete(dir, true)
Directory.CreateDirectory dir |> ignore
// Small modules: a block's first call looks for its body among its module's members.
let perFile = 40
cases
|> List.chunkBySize perFile
|> List.iteri (fun i chunk ->
    let body =
        [ yield "// Generated by generate.fsx: do not edit."
          yield sprintf "module Differential.Cases%03d" i
          yield ""
          yield "open FSharp.Interop.Dlr"
          yield "open Differential.Support"
          yield ""
          for c in chunk do
            yield "[<ReflectedDefinition>]"
            yield sprintf "let %s %s : string =" (identifier c.Id) c.Params
            yield! indent c.Lines
            yield "" ]
    File.WriteAllLines(Path.Combine(dir, sprintf "Cases%03d.g.fs" i), body))
printfn "%d cases in %d files" cases.Length ((cases.Length + perFile - 1) / perFile)
