// Writes Tests/Captures.fs: a covering set of the grammar's cases (Grammar.fsx), each pinned to
// what a run of run.sh found: its value (Debug's) and whether Release refuses it. The set covers
// every three values any three dimensions take together, so the tests in CI see each interaction
// of three the full run does (a bug needing three, as the mutable alias of a split tuple did,
// shows), and a change in what Release does, better or worse, fails a test until pinned again.
//   ./run.sh, then dotnet fsi pin.fsx

#load "Grammar.fsx"

open System
open System.Collections.Generic
open System.IO
open System.Text.RegularExpressions
open Grammar

let read path =
    File.ReadAllLines path |> Array.map (fun l -> l.Split '\t') |> Array.map (fun a -> a.[0], a) |> dict

let debug = read (Path.Combine(__SOURCE_DIRECTORY__, "obj/differential/debug.txt"))
let release = read (Path.Combine(__SOURCE_DIRECTORY__, "obj/differential/release.txt"))

/// A greedy covering set (lazily re-scored; small, not proven the smallest) of one family's
/// cases, covering every triple of values across every three dimensions.
let cover (family: Case list) =
    let tripleOf (c: Case) =
        let d = c.Dims |> List.tail |> Array.ofList
        [ for i in 0 .. d.Length - 3 do
            for j in i + 1 .. d.Length - 2 do
              for k in j + 1 .. d.Length - 1 ->
                sprintf "%d=%s|%d=%s|%d=%s" i d.[i] j d.[j] k d.[k] ]
    let triples = family |> List.map (fun c -> c, tripleOf c) |> Array.ofList
    let uncovered = HashSet<string>(triples |> Seq.collect snd)
    let score (_, ts: string list) = ts |> List.sumBy (fun t -> if uncovered.Contains t then 1 else 0)
    // Lazy greedy: a stale score only overstates, so re-score the top until it holds.
    let queue = SortedSet<int * int>(Comparer.Create(fun (s1, i1) (s2, i2) -> if s1 <> s2 then compare s2 s1 else compare i1 i2))
    triples |> Array.iteri (fun i t -> queue.Add((score t, i)) |> ignore)
    let chosen = ResizeArray<Case>()
    while uncovered.Count > 0 do
        let (stale, i) = queue.Min
        queue.Remove((stale, i)) |> ignore
        let fresh = score triples.[i]
        if fresh > 0 then
            if queue.Count = 0 || fresh >= fst queue.Min then
                chosen.Add(fst triples.[i])
                for t in snd triples.[i] do uncovered.Remove t |> ignore
            else queue.Add((fresh, i)) |> ignore
    List.ofSeq chosen

let pinned = (cases |> List.filter (fun c -> c.Dims.Head = "one") |> cover) @ (cases |> List.filter (fun c -> c.Dims.Head = "two") |> cover)

/// The grammar's support types, as Tests/Fixtures.fs names them.
let forTests (line: string) =
    let line = Regex.Replace(line, @"\bS\(", "CaptureValue(")
    let line = Regex.Replace(line, @": S\b", ": CaptureValue")
    line.Replace("applyInline", "CaptureSupport.applyInline")

let isError (s: string) = s.Contains "Exception: "
let quote (s: string) = "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\""

let chunks = pinned |> List.chunkBySize 40
let caseModule i = sprintf "CaptureCases%02d" i

let body =
    [ yield "// Generated by Differential/pin.fsx from a run of Differential/run.sh: do not edit (see #200)."
      yield "// A covering set of the capture grammar's cases (every three values of any three of its"
      yield "// dimensions together), each pinned to its Debug value and whether Release refuses it."
      yield "namespace Tests"
      yield ""
      yield "// `Data` is the machine's own field's name, the collision the cases test: `| Some Data ->`"
      yield "// binds it in a pattern. Not every case reads `seed` and `seed2`."
      yield "#nowarn \"49\" \"1182\""
      yield ""
      yield "// The two-variable shapes are the point: the analyzer reports them at build time."
      yield "// fsharpanalyzer: ignore-region-start DLR007"
      // Modules of 40: a block's first call looks for its body among its module's members.
      for i, chunk in List.indexed chunks do
          yield "[<ReflectedDefinition>]"
          yield sprintf "module internal %s =" (caseModule i)
          yield "    open FSharp.Interop.Dlr"
          yield ""
          for c in chunk do
              yield! indent (sprintf "let %s %s : string =" (identifier c.Id) (forTests c.Params) :: indent (c.Lines |> List.map forTests))
              yield ""
      yield "// fsharpanalyzer: ignore-region-end DLR007"
      yield ""
      // Not reflected: as a quotation, the list is one level deep per case, past Debug's stack.
      yield "module Captures ="
      yield "    open AnyUnit.Style.Xunit"
      yield "    open AnyUnit.Style.FsUnit"
      yield "    open FSharp.Interop.Dlr"
      yield ""
      yield "    /// Each case: its name, a call, its value, and whether Release refuses it."
      // An array: a list literal is a Cons per case, one level deep each, past an analyzer's stack.
      yield "    let private pinned : (string * (obj -> string) * string * bool)[] ="
      yield "        [|"
      for i, chunk in List.indexed chunks do
        for c in chunk do
          let d, r = debug.[identifier c.Id], release.[identifier c.Id]
          if isError d.[1] then failwithf "%s fails in Debug: %s" c.Id d.[1]
          let refused = r.[1].StartsWith "DlrTranslationException"
          if not refused && r.[1] <> d.[1] then failwithf "%s is wrong in Release: %s, not %s" c.Id r.[1] d.[1]
          let x =
              if not (c.Params.Contains "(x: " || c.Params.Contains "(Data: " || c.Params.Contains "(matchValue: ") then ""
              elif c.Params.EndsWith "S)" then " (CaptureValue 5)"
              elif c.Params.EndsWith "int * int)" then " (5, 70)"
              else " 5"
          yield sprintf "          %s, (fun o -> %s.%s o 7 11%s), %s, %b" (quote c.Id) (caseModule i) (identifier c.Id) x (quote d.[1]) refused
      yield "        |]"
      yield ""
      yield "    [<Fact>]"
      yield "    let ``each pinned capture case reads its Debug value, or Release refuses it as pinned`` () ="
      yield "        let release ="
      yield "#if DEBUG"
      yield "            false"
      yield "#else"
      yield "            true"
      yield "#endif"
      yield "        let failures ="
      yield "            [ for name, run, expected, refused in pinned do"
      yield "                Ticks.Reset()"
      yield "                match (try Ok(run (box (CaptureEcho()))) with :? DlrTranslationException as e -> Error e.Message) with"
      yield "                | Ok value when value <> expected -> yield sprintf \"%s: %s, not %s\" name value expected"
      yield "                | Ok _ when release && refused -> yield sprintf \"%s: now runs in Release (pinned as refused)\" name"
      yield "                | Error message when not (release && refused) -> yield sprintf \"%s: %s\" name message"
      yield "                | _ -> () ]"
      yield "        failures |> should be Empty" ]

File.WriteAllLines(Path.Combine(__SOURCE_DIRECTORY__, "../Tests/Captures.fs"), body)
printfn "%d of %d cases pinned (%d one, %d two)" pinned.Length cases.Length (pinned |> List.filter (fun c -> c.Dims.Head = "one") |> List.length) (pinned |> List.filter (fun c -> c.Dims.Head = "two") |> List.length)
